Fix JSON deserialize problem
When deserialize response JSON to NeutronLbPoolV2, the field `sessionPersistence` is abstract types(interface), which did not specify the implementation class. Exception has occurred.
```
com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of org.openstack4j.model.network.ext.SessionPersistence
```